### ISSUE TITLE
Package.json does not correctly direct the build

### ISSUE THREAD

**Issue by paulhands** [d3fc/d3fc-annotation#23]
When trying to import annotationSvgLine from 'd3fc-annotation' I received the following error:

C:\Dev\ThreeTrader\Client\node_modules\d3fc-annotation\index.js:1
(function (exports, require, module, __filename, __dirname) { export { default as annotationSvgBand } from './src/svg/band';

Upon investigation it appears your package.json file does not have a "main" option to direct the build correctly

**Comment by chrisprice** [comment]
Thanks for the fix!

**Comment by ColinEberhardt** [comment]
@chrisprice - have you checked the other d3fc projects to see if they also have the same issue?

**Comment by chrisprice** [comment]
I delegated that particular task 🙂
